QuizStep/Controllers/QuizController.cs
using Microsoft.AspNetCore.Mvc;
using QuizStep.Data;
using QuizStep.Data.Entity;
using QuizStep.Models.QuizModels;
using QuizStep.Services.Quiz;

namespace QuizStep.Controllers;

public class QuizController : Controller
{
    private readonly DataContext _dataContext;
    private readonly IQuizService _quizService;

    public QuizController(DataContext dataContext, IQuizService quizService)
    {
        _dataContext = dataContext;
        _quizService = quizService;
    }

    public IActionResult StartTest([FromRoute] string id)
    {
        Guid studentId;
        try
        {
            studentId = Guid.Parse(HttpContext.Session.GetString("authUserId"));
        }
        catch
        {
            return RedirectToAction("Auth", "Account");
        }

        Guid testId;
        try
        {
            testId = Guid.Parse(id);
        }
        catch
        {
            return RedirectToAction("Main", "Home");
        }

        if (_dataContext.Journals.Any(j => j.UserId == studentId && j.TestId == testId))
        {
            // уже открыт тест
        }
        else
        {
            _dataContext.Journals.Add(new()
            {
                Id = Guid.NewGuid(),
                UserId = studentId,
                TestId = testId,
                IsPassed = false,
            });
        }

        List<QuestionModel> questions = _dataContext.Questions
            .Where(q => q.TestId == testId)
            .Select(qs => new QuestionModel()
            {
                Id = qs.Id,
                TestId = qs.TestId.ToString(),
                Text = qs.Text,
                Answers = _dataContext.Answers
                    .Where(a => a.QuestionId == qs.Id)
                    .Select(a => new AnswerModel()
                    {
                        Id = a.Id,
                        QuestionId = a.QuestionId,
                        Text = a.Text,
                        IsRight = a.IsRight
                    })
                    .ToList()
            })
            .ToList();
        HttpContext.Session.SetString("questions", _quizService.SerializeQuestions(questions));
        ViewBag.TotalQuestions = questions.Count;
        return View("DisplayTest");
    }

    public IActionResult DisplayTest([FromRoute] String id)
    {
        Guid studentId;
        try
        {
            studentId = Guid.Parse(HttpContext.Session.GetString("authUserId"));
        }
        catch
        {
            return RedirectToAction("Auth", "Account");
        }

        Guid testId;
        try
        {
            testId = Guid.Parse(id);
        }
        catch
        {
            return RedirectToAction("Main", "Home");
        }

        // проверка существует ли уже начатый тест исходя из журнала
        if (_dataContext.Journals.Any(j => j.UserId == studentId && j.TestId == testId))
        {
            // уже открыт тест
        }
        else
        {
            _dataContext.Journals.Add(new()
            {
                Id = Guid.NewGuid(),
                UserId = studentId,
                TestId = testId,
                IsPassed = false
            });
        }

        List<QuestionModel> questions = _dataContext.Questions
            .Where(q => q.TestId == testId)
            .Select(qs => new QuestionModel()
            {
                Id = qs.Id,
                TestId = qs.TestId.ToString(),
                Text = qs.Text,
                Answers = _dataContext.Answers
                    .Where(a => a.QuestionId == qs.Id)
                    .Select(a => new AnswerModel()
                    {
                        Id = a.Id,
                        QuestionId = a.QuestionId,
                        Text = a.Text,
                        IsRight = a.IsRight
                    })
                    .ToList(),
                CheckedAnswer = null!,
                Index = 0
            })
            .ToList();
        HttpContext.Session.SetString("questions", _quizService.SerializeQuestions(questions));
        ViewBag.TotalQuestions = questions.Count;
        /////////////////////////////////////////////////
        var currentQuestion = questions.First();
        ViewBag.CurrentQuestion = currentQuestion;
        ViewBag.QuestionIndex = 0;
        _dataContext.SaveChanges();
        return View(currentQuestion);
    }

    public IActionResult NextQuestion(int questionIndex)
    {
        var questions = _quizService.DeserializeQuestions(HttpContext.Session.GetString("questions"));
        ViewBag.TotalQuestions = questions.Count;
        var nextQuestion = questions[questionIndex];
        ViewBag.CurrentQuestion = nextQuestion;
        ViewBag.QuestionIndex = questionIndex;
        return View("DisplayTest", nextQuestion);
    }

    public IActionResult PreviousQuestion(int questionIndex)
    {
        var questions = _quizService.DeserializeQuestions(HttpContext.Session.GetString("questions"));
        ViewBag.TotalQuestions = questions.Count;
        var prevQuestion = questions[questionIndex];
        ViewBag.CurrentQuestion = prevQuestion;
        ViewBag.QuestionIndex = questionIndex;
        return View("DisplayTest", prevQuestion);
    }

    public IActionResult UnifiedPagination(QuestionModel model, string button, int questionIndex)
    {
        if (HttpContext.User.Identity is not null && HttpContext.User.Identity.IsAuthenticated)
        {
            var questions = _quizService.DeserializeQuestions(HttpContext.Session.GetString("questions"));
            ViewBag.TotalQuestions = questions.Count;
            Guid selectedItem;
            try
            {
                selectedItem = Guid.Parse(model.CheckedAnswer);
            }
            catch
            {
                selectedItem = Guid.Empty;
            }


            var question = questions[questionIndex];
            var answer = _dataContext.Answers.FirstOrDefault(a => a.Id == selectedItem);
            if (question is not null && answer is not null)
            {
                var studentId = Guid.Parse(HttpContext.Session.GetString("authUserId"));
                // проверка на существование ответа на этот вопрос
                StudentAnswers studentAnswer = null!;
                try
                {
                    studentAnswer = _dataContext.StudentAnswers.FirstOrDefault(sa =>
                        sa.UserId == Guid.Parse(HttpContext.Session.GetString("authUserId")) &&
                        sa.TestId == Guid.Parse(question.TestId) &&
                        sa.QuestionId == question.Id);
                }
                catch
                {
                }

                if (studentAnswer is not null)
                {
                    _dataContext.StudentAnswers.Remove(studentAnswer);
                }

                _dataContext.StudentAnswers.Add(new()
                {
                    Id = Guid.NewGuid(),
                    UserId = studentId,
                    TestId = Guid.Parse(question.TestId),
                    QuestionId = question.Id,
                    AnswerId = answer.Id,
                    IsRight = answer.IsRight,
                });
            }

            switch (button)
            {
                case "previous":
                {
                    var prevQuestion = questions[questionIndex - 1];
                    ViewBag.CurrentQuestion = prevQuestion;
                    ViewBag.QuestionIndex = questionIndex - 1;
                    _dataContext.SaveChanges();
                    return View("DisplayTest", prevQuestion);
                }
                case "next":
                {
                    var nextQuestion = questions[questionIndex + 1];
                    ViewBag.CurrentQuestion = nextQuestion;
                    ViewBag.QuestionIndex = questionIndex + 1;
                    _dataContext.SaveChanges();
                    return View("DisplayTest", nextQuestion);
                }
                case "finish":
                    var testId = Guid.Parse(question.TestId);
                    var studentId = Guid.Parse(HttpContext.Session.GetString("authUserId"));
                    // создаем модель TestResultModel на основе Journal
                    var journal =
                        _dataContext.Journals.FirstOrDefault(j => j.TestId == testId && j.UserId == studentId);
                    if (journal is not null)
                    {
                        // высчитываем результат
                        var studentAnswers = _dataContext.StudentAnswers
                            .Where(sa => sa.UserId == studentId && sa.TestId == testId)
                            .ToList();
                        var totalRightAnswers = studentAnswers.Count(sa => sa.IsRight);
                        var result = (int)Math.Round((double)totalRightAnswers / studentAnswers.Count * 100);
                        if (totalRightAnswers > 0 && studentAnswers.Count > 0 && result >= 60)
                        {
                            journal.Result = $"{result}%";
                            journal.IsPassed = true;
                        }
                        else
                        {
                            journal.Result = $"{result}%";
                            journal.IsPassed = false;
                        }

                        _dataContext.SaveChanges();
                        return View("TestResult", new TestResultModel()
                        {
                            Result = journal.Result,
                            IsPassed = journal.IsPassed
                        });
                    }

                    break;
                default:
                    throw new Exception("Invalid button");
            }

            return NotFound();
        }

        return RedirectToAction("Auth", "Account");
    }
}

QuizStep/Views/Quiz/DisplayTest.cshtml
@using Microsoft.EntityFrameworkCore.Metadata.Internal
@model QuizStep.Models.QuizModels.QuestionModel

@{
    ViewData["Title"] = "Test";
}
<input type="hidden" asp-for="TestId" value="@Model.TestId"/>
<div class="album py-2 bg-light">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12  col-xs-12">
                <div class="shadow p-3 mb-1 bg-white rounded" style="border-left: 5px solid #4CAF50">
                    @Model.Text
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 col-sm-12  col-xs-12">
                <div class="shadow pt-2 mb-2 bg-white rounded" style="border-left: 5px solid #2196F3">
                    <form method="post" asp-controller="Quiz" asp-action="UnifiedPagination">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="card" style="margin:10px 0">
                                    <ul class="list-group list-group-flush">
                                        @foreach (var answer in Model.Answers)
                                        {
                                            <li class="list-group-item">
                                                <label class="checkboxRadio">
                                                    <input  type="radio" asp-for="@Model.CheckedAnswer" value="@answer.Id"/>
                                                    <span class="primary"></span>
                                                </label>
                                                @answer.Text
                                            </li>
                                        }
                                    </ul>
                                </div>
                                
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="nav-scroller py-1 mb-2 p-3">
                                        <div class=" nav d-flex dataTables_paginate paging_simple_numbers ">
                                            <ul class="pagination pagination-md flex-sm-wra">
                                                @if (ViewBag.QuestionIndex > 0)
                                                {
                                                    <li class="paginate_button page-item">
                                                        <button class="page-link" name="button" value="previous" onclick="changeQuestionIndex(-1)">
                                                            Попереднє
                                                            <input id="questionIndex" name="questionIndex" type="hidden" value="@ViewBag.QuestionIndex"/>
                                                        </button>
                                                    </li>
                                                }
                                                else
                                                {
                                                    <li class="paginate_button page-item disabled">
                                                        <a class="page-link" >
                                                            @* href="@Url.Action("PreviousQuestion", new { questionIndex = ViewBag.QuestionIndex - 1 })"> *@
                                                            Попереднє
                                                        </a>
                                                    </li>
                                                }
                                                @if (ViewBag.QuestionIndex < ViewBag.TotalQuestions - 1)
                                                {
                                                    <li class="paginate_button page-item">
                                                        <button class="page-link" name="button" value="next" onclick="changeQuestionIndex(1)">
                                                            Наступне
                                                            <input id="questionIndex" name="questionIndex" type="hidden" value="@ViewBag.QuestionIndex"/>
                                                            @* <a class="page-link" href="@Url.Action("NextQuestion", new { questionIndex = ViewBag.QuestionIndex + 1 })"> *@
                                                            @*      Next *@
                                                            @*  </a> *@
                                                        </button>
                                                    </li>
                                                }
                                                else
                                                {
                                                    <li class="paginate_button page-item disabled">
                                                        <a class="page-link"
                                                           href="@Url.Action("NextQuestion", new { questionIndex = ViewBag.QuestionIndex + 1 })">
                                                            Наступне
                                                        </a>
                                                    </li>
                                                }
                                                <li class="paginate_button page-item">
                                                    <button class="page-link" name="button" value="finish">
                                                        Завершити тест
                                                    </button>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>


<script>
    function changeQuestionIndex(offset) {
            var questionIndexInput = document.getElementById('questionIndex');
            if (questionIndexInput) {
                var currentValue = parseInt(questionIndexInput.value) || 0; // Значение по умолчанию, если questionIndex не содержит числовое значение
                questionIndexInput.value = currentValue + offset;
                @ViewBag.QuestionIndex = questionIndexInput.value; 
            }
        // var questionIndexInput = document.getElementById('questionIndex');
        // if (questionIndexInput) {
        //     questionIndexInput.value = parseInt(questionIndexInput.value) - offset;
        //    
        //     console.log(questionIndexInput.value);
        // }
    }
</script>

QuizStep/Views/Quiz/TestResult.cshtml
@model QuizStep.Models.QuizModels.TestResultModel

@{
    ViewData["Title"] = "TestResult";
}

<div class="container d-flex justify-content-center align-items-center center-block">
	<div class="row text-center">
        <div class="text-center">
            @if (@Model.IsPassed)
            {
                <br><br>
                <h2 class="text-success">Ви успішно сдали тест!</h2>
                <p style="font-size:20px;color:#5C5C5C;">
                    Ваш результат: @Model.Result.<br/>
                    Щоб повернутися до головної сторінки натисніть кнопку нижче. 
                </p>
                <a  class="btn btn-success" asp-action="Main" asp-controller="Home">Повернутися</a>
                <br><br>
            }
            else if(!@Model.IsPassed)
            {
                <br><br>
                <h2 class="text-danger">Ви не сдали тест!</h2>
                <p style="font-size:20px;color:#5C5C5C;">
                    Ваш результат: @Model.Result.<br/>
                    Щоб повернутися до головної сторінки натисніть кнопку нижче. 
                </p>
                <a class="btn btn-danger" asp-action="Main" asp-controller="Home">Повернутися</a>
                <br><br>
            }
        </div>
    </div>
</div>